### ISSUE TITLE
Installation example doesn't work ("not in gzip format")

### ISSUE THREAD

**Issue by the-bass** [humanmade/go-anonymize-mysqldump#15]
I just tried to follow the installation instructions for Mac. I ran

```sh
curl -OL https://github.com/humanmade/go-anonymize-mysqldump/releases/download/latest/go-anonymize-mysqldump_darwin_amd64.gz
```

and then tried

```sh
gunzip go-anonymize-mysqldump_darwin_amd64.gz
```

However, the latter returns
```
gunzip: go-anonymize-mysqldump_darwin_amd64.gz: not in gzip format
```

**Comment by svandragt** [comment]
Hi @the-bass it looks like links to zip files do not work for the `latest` version but if you go to https://github.com/humanmade/go-anonymize-mysqldump/releases/latest it will redirect to the latest version (0.3.0) and you can use any of the links listed on the releases page. For you I think that's https://github.com/humanmade/go-anonymize-mysqldump/releases/download/0.3.0/go-anonymize-mysqldump_darwin_amd64.gz

**Comment by the-bass** [comment]
That did the trick! Thanks a lot, @svandragt!
